[Week5/#9] 5주차 워크북 미션
DS-UMC-7th/UMC-7th-Mati pull request #10
Opened 2024-11-06 20:40 UTC by alwn8918

## 📌 관련 이슈번호

- Closes #9 

## ✅ Key Changes

> 이번 PR에서 작업한 내용을 간략히 설명해주세요

1. 작업 내용
- 메인 화면 스크롤뷰로 변경
- 컬렉션뷰 2개 추가 구현

## 📢 To Reviewers (Part Leader)

- 스크롤뷰 내부 요소들에 오른쪽 여백이 생기는데.. 이유를 못 찾겠어요..

## 📸 스크린샷

https://github.com/user-attachments/assets/89a955ce-8f79-4d64-a103-2489d6f6dd3e

## 🔗 참고 자료

2024-11-12 23:47 UTC, pookey1104 approved these changes
과제 제출 조건, 순서에 따라 잘 구현해주신 것 같습니다 👍🏻
5주차 과제도 수고 많으셨습니다! ⚒️

2024-11-12 23:50 UTC, pookey1104 requested changes
✚ 4주차 merge 이후로 충돌이 발생한 것으로 보여 해결해주시면 5주차 과제 merge 진행하도록 하겠습니다!
@alwn8918

2024-11-13 19:52 UTC, alwn8918 commented
해결 했습니다!

2024-11-14 06:15 UTC, pookey1104 approved these changes
확인했습니다! 감사합니다 😊

2024-11-14 06:16 UTC, merged